name: Export Power Platform Solution (Dev)

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Power Platform CLI
      run: |
        npm install -g pac@1.8.0

    - name: Authenticate with Power Platform
      run: |
        pac auth create --url 'https://demo001.crm8.dynamics.com/' --clientId '2c34728a-634b-414c-b7e4-e904ead4b2c1' --clientSecret '8xN8Q~CNcHgj0dCgkl~B8Uc31LX93CUu3fETCdg.' --tenant '807cb068-493f-40b4-b067-712d94fa7730'

    - name: Export Solution from Dev (Unmanaged)
      run: |
        pac solution export --name 'ADCBMasterConfigurations' --path UnmanagedSolution.zip --managed false

    - name: Unpack solution to folder
      run: |
        pac solution unpack --zipfile UnmanagedSolution.zip --folder powerplatform/solution --packagetype Unmanaged

    - name: Commit unpacked solution
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add powerplatform/solution
        git commit -m "Exported solution from Dev (Unmanaged)" || echo "No changes to commit"
        git push
